services:
  frontend:
    build:
      context: ./baj-frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    networks:
      - dokploy-network
    labels:
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

  dashboard:
    build:
      context: ./baj-dashboard
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    networks:
      - dokploy-network
    labels:
      - "traefik.http.services.dashboard.loadbalancer.server.port=3000"

networks:
  dokploy-network:
    external: true
