services:
  frontend:
    build:
      context: ./baj-frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    networks:
      - dokploy-network

  dashboard:
    build:
      context: ./baj-dashboard
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
